[package]
name = "lila-openingexplorer3"
version = "0.1.0"
publish = false
description = "An opening explorer for lichess.org"
homepage = "https://explorer.lichess.ovh"
repository = "https://github.com/niklasf/lila-openingexplorer3"
readme = "README.md"
license = "AGPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["games"]
keywords = ["chess", "lichess"]
edition = "2018"

[dependencies]
axum = "0.2"
byteorder = "1"
clap = "3.0.0-beta.4"
futures-util = "0.3"
log = "0.4"
reqwest = { version = "0.11", features = ["stream"] }
rocksdb = "0.17"
rustc-hash = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "1"
sha-1 = "0.9"
shakmaty = { version = "0.20", features = ["variant"], path = "../shakmaty" }
smallvec = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["io-util"] }
tokio-util = { version = "0.6", features = ["io"] }

[dev-dependencies]
quickcheck = "1"
