[package]
name = "index-pgn"
version = "0.0.0"
publish = false

[dependencies]
pgn-reader = "0.5"
memmap = "0.6"
madvise = "0.1"
btoi = "0.3"
rand = "0.4"
reqwest = "0.8"

[[bin]]
name = "index-lichess"
path = "src/lichess.rs"
